config/routes.rb
Rails.application.routes.draw do
  resources :requests
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :users do
    member do
      post :enable_multi_factor_authentication, to: 'users/multi_factor_authentication#verify_enable'
      post :disable_multi_factor_authentication, to: 'users/multi_factor_authentication#verify_disabled'
    end
  end

  get :protected, to: 'visitors#protected'
  
  root 'static#homepage'
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:confirmation, :user_id, :job_id)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if current_user.email != 'desmond@dsrecruitment.sg' %>
  <div class="field" hidden="true">
    <%= f.label :confirmation %>
    <%= f.select :confirmation, [['Pending','Pending'],['Confirmed','Confirmed'], ['Slots Filled','Slots Filled']] %>
  </div>

  <div class="field" hidden="true" >
    <%= f.label :user_id %>
    <%= f.text_field :user_id, :value => current_user.id %>
  </div>

  <div class="field" hidden="true">
    <%= f.label :job_id %>
    <%= f.text_field :job_id, :value => params[:jobs_id] %>
  </div>

<% else %>

<div class="field" >
  <%= f.label :confirmation %>
  <%= f.select :confirmation, [['Pending','Pending'],['Confirmed','Confirmed'], ['Slots Filled','Slots Filled']] %>
</div>

<div class="field">
  <%= f.label :user_id %>
  <%= f.text_field :user_id, :value => @request.user_id %>
</div>

<div class="field">
  <%= f.label :job_id %>
  <%= f.text_field :job_id, :value => @request.job_id %>
</div>

<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<% if current_user.email != 'desmond@dsrecruitment.sg' %>

<h1>Confirmed Slots</h1>

  <table class = "table table-hover">
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
    <% if current_user.email == request.user.email && request.confirmation == "Confirmed" && request.job.completed == false %>
      <tr>
        <td><%= request.job.location %></td>
        <td><%= request.job.date %></td>
        <td><%= request.job.start_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= request.job.end_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= link_to 'Cancel', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
          <% end %>
    <% end %>
  </tbody>
</table>

<h1>Pending Confirmation</h1>

  <table class = "table table-hover">
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
    <% if current_user.email == request.user.email && request.confirmation == "Pending" && request.job.completed == false%>
      <tr>
        <td><%= request.job.location %></td>
        <td><%= request.job.date %></td>
        <td><%= request.job.start_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= request.job.end_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= link_to 'Cancel', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
          <% end %>
    <% end %>
  </tbody>
</table>

<h1>Failed</h1>

  <table class = "table table-hover">
  <thead>
    <tr>
      <th>Location</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
    <% if current_user.email == request.user.email && request.confirmation == "Slots Filled" && request.job.completed == false   %>
      <tr>
        <td><%= request.job.location %></td>
        <td><%= request.job.date %></td>
        <td><%= request.job.start_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= request.job.end_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= request.confirmation%></td>
      </tr>
          <% end %>
    <% end %>
  </tbody>
</table>

<h1>Completed Jobs</h1>

<table class = "table table-hover">
<thead>
  <tr>
    <th>Location</th>
    <th>Date</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @requests.each do |request| %>
  <% if current_user.email == request.user.email && request.confirmation == "Confirmed" && request.job.completed == true %>
    <tr>
      <td><%= request.job.location %></td>
      <td><%= request.job.date %></td>
      <td><%= request.job.start_time.to_time.strftime("%H:%M %p") %></td>
      <td><%= request.job.end_time.to_time.strftime("%H:%M %p") %></td>
    </tr>
        <% end %>
  <% end %>
</tbody>
</table>

<% else %>

<h1>All Jobs</h1>

  <table class = "table table-hover">
  <thead>
    <tr>
      <th>Requested By</th>
      <th>Requestee Contact</th>
      <th>Job ID</th>
      <th>Location</th>
      <th>Date</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
    <% if request.job.completed == false %>
      <tr>
        <td><%= request.user.name %></td>
        <td><%= request.user.contact %></td>
        <td><%= request.job_id %></td>
        <td><%= request.job.location %></td>
        <td><%= request.job.date %></td>
        <td><%= request.job.start_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= request.job.end_time.to_time.strftime("%H:%M %p") %></td>
        <td><%= request.confirmation %>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Cancel', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
          <% end %>
    <% end %>
  </tbody>
</table>



<% end %>

app/views/requests/new.html.erb
<h1>Confirm your booking?</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p>
  <strong>Booked by:</strong>
  <%= @request.user.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @request.job.location %>
</p>

<p>
  <strong>Start Time:</strong>
  <%= @request.job.start_time.to_time.strftime("%H:%M %p") %>
</p>

<p>
  <strong>End Time:</strong>
  <%= @request.job.end_time.to_time.strftime("%H:%M %p") %>
</p>

<p>
  <strong>Status:</strong>
<%= @request.confirmation%>

</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>